NumPy array and basics

In [1]:
import numpy as np

 Array Creation

In [ ]:
# 1D array creation
arr_1d = np.array([10,20,30,40])
print(arr_1d, type(arr_1d))
arr_2d = np.array([
                    [10,20,30],
                    [40,50,60]
                 ])
print(arr_2d, type(arr_2d))
arr = np.array([
                    [10,20,45.5],
                    [40,50,60]
                 ])
print(arr, type(arr))

[10 20 30 40] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'>
[[10.  20.  45.5]
 [40.  50.  60. ]] <class 'numpy.ndarray'>


List v/s NumPy Array 

In [8]:
#Ap1
cost_list = [10,20,30,40]
print("Selling List ",cost_list*2) #Not possible
cost_arr = np.array([10,20,30,40])
print("Selling Arr ",cost_arr*2)

#Ap2
d1_list = [10,20,30,40]
d2_list = [20,15,45,50]
print("Total sale ", d1_list+d2_list) #Not possible
d1_arr = np.array([10,20,30,40])
d2_arr = np.array([20,15,45,50])
print("Total sale ", d1_arr+d2_arr)


Selling List  [10, 20, 30, 40, 10, 20, 30, 40]
Selling Arr  [20 40 60 80]
Total sale  [10, 20, 30, 40, 20, 15, 45, 50]
Total sale  [30 35 75 90]


In [3]:
import time as t
#List
start = t.time()
list_time = [i*2 for i in range(1000000)]
end = t.time()
print("List operation:", end-start)

#Numpy array
start = t.time()
arr_time = np.arange(1000000)*2
end = t.time()
print("Array operation:", end-start)

List operation: 0.07614350318908691
Array operation: 0.006818056106567383


### Creating array from scratch

In [8]:
#Zeros
zeros = np.zeros((2,3))
print("Zeros Matrix:\n", zeros)

#Ones
ones = np.ones((3,2))
print("Ones Matrix:\n", ones)

#Full
full = np.full((3,3),7)
print("Full with num Matrix:\n", full)

#Random
random = np.random.random((2,2))
print("Random Matrix(0 to 1):\n", random)

#Sequence  start, stop, step
seq = np.arange(10,31)
print("Sequence of 10 to 30 :\n", seq)


Zeros Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full with num Matrix:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random Matrix(0 to 1):
 [[0.86231184 0.84832577]
 [0.64121235 0.98688635]]
Sequence of 10 to 30 :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


### Vector, Matrix and Tensor

In [15]:
vector = np.array([10,20,30,40])
print("Vector:\n", vector)
matrix = np.array([[10,20,30],
                   [40,50,60]]
                   )
print("Matrix:\n", matrix)
tensor = np.array([
                    [[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]]
                ])
print("Tensor:\n",tensor)
print("Dimension:", tensor.ndim)



Vector:
 [10 20 30 40]
Matrix:
 [[10 20 30]
 [40 50 60]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension: 3


### Array properties

In [18]:
arr = np.array([[1,2,3],
               [4,5,6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Dtype:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Dtype: int64


### Array Reshaping

In [22]:
arr = np.arange(12)
print("Array:",arr)
#Reshaping
reshape = arr.reshape((3,4))
print("Reshape:\n",reshape)
mat = np.array([[10,20,30],
                [40,50,60]]
                )
fl = mat.flatten()
print(fl)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10 20 30 40 50 60]
