### NumPy Array Operation

In [2]:
import numpy as np

In [5]:
arr = np.array([10,20,30,40,50])
print("Basic Slicing:", arr[:4])
print("Slicing with step:", arr[0:5:2])
print("Negative index:", arr[-1])



Basic Slicing: [10 20 30 40]
Slicing with step: [10 30 50]
Negative index: 50


In [15]:
arr_2d = np.array([[1,2,3,10],
                   [4,5,6,20],
                   [7,8,9,30]])
print("Specific element:", arr_2d[1,2])
print("Entire row:\n", arr_2d[1:,2:])
#Last two rows
print("Last two rows:\n", arr_2d[1:,0:])
print("Entire one col:",arr_2d[:,1])
print("Entire col:",arr_2d[:,1:])

sales = np.array([[1,2000,3000,1000],       #Res1
                  [2,5000,6000,2000],       #Res2
                  [3,8000,9000,3000]])      #Res3
print("Last 2 year sales", sales[1,2:])

Specific element: 6
Entire row:
 [[ 6 20]
 [ 9 30]]
Last two rows:
 [[ 4  5  6 20]
 [ 7  8  9 30]]
Entire one col: [2 5 8]
Entire col: [[ 2  3 10]
 [ 5  6 20]
 [ 8  9 30]]
Last 2 year sales [6000 2000]


### Sorting

In [21]:
arr_1d = np.array([3,5,2,9,5,6,1,7])
print("Sorting 1d array", sorted(arr_1d))
print("Sorting 1d array", np.sort(arr_1d))

arr_2d = np.array([[2,1],
                   [3,2],
                   [1,3]])
print("Sorting 2d array", np.sort(arr_2d))
# axis=0 for col
print("Sorting 2d array", np.sort(arr_2d,axis=0))
# axis=1 for row
print("Sorting 2d array", np.sort(arr_2d,axis=1))




Sorting 1d array [np.int64(1), np.int64(2), np.int64(3), np.int64(5), np.int64(5), np.int64(6), np.int64(7), np.int64(9)]
Sorting 1d array [1 2 3 5 5 6 7 9]
Sorting 2d array [[1 2]
 [2 3]
 [1 3]]
Sorting 2d array [[1 1]
 [2 2]
 [3 3]]
Sorting 2d array [[1 2]
 [2 3]
 [1 3]]


### Filter

In [22]:
number = np.array([3,5,2,9,5,6,1,7])
even_number = number[number % 2 == 0]
print("Even Number:",even_number)

Even Number: [2 6]


### Filter with mask

In [3]:
marks = np.array([67,34,10,23,50,97,54])
mask_pass = marks > 35
print("More than 35(Mask): ",mask_pass)

More than 35(Mask):  [ True False False False  True  True  True]


### Index

In [5]:
sales = np.array([25000,12000,65000,80000])
idc = [1,3]
res = sales[idc]
print("Find value in index:",res)

Find value in index: [12000 80000]
