NumPy array and basics

In [1]:
import numpy as np

 Array Creation

In [ ]:
# 1D array creation
arr_1d = np.array([10,20,30,40])
print(arr_1d, type(arr_1d))
arr_2d = np.array([
                    [10,20,30],
                    [40,50,60]
                 ])
print(arr_2d, type(arr_2d))
arr = np.array([
                    [10,20,45.5],
                    [40,50,60]
                 ])
print(arr, type(arr))

[10 20 30 40] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'>
[[10.  20.  45.5]
 [40.  50.  60. ]] <class 'numpy.ndarray'>


List v/s NumPy Array 

In [8]:
#Ap1
cost_list = [10,20,30,40]
print("Selling List ",cost_list*2) #Not possible
cost_arr = np.array([10,20,30,40])
print("Selling Arr ",cost_arr*2)

#Ap2
d1_list = [10,20,30,40]
d2_list = [20,15,45,50]
print("Total sale ", d1_list+d2_list) #Not possible
d1_arr = np.array([10,20,30,40])
d2_arr = np.array([20,15,45,50])
print("Total sale ", d1_arr+d2_arr)


Selling List  [10, 20, 30, 40, 10, 20, 30, 40]
Selling Arr  [20 40 60 80]
Total sale  [10, 20, 30, 40, 20, 15, 45, 50]
Total sale  [30 35 75 90]
